### PR TITLE
Dev lmod support

### LINKED ISSUE #34: Modules are clunky and meh.
So the rwth uses Lmod now: https://lmod.readthedocs.io/en/latest/#

That appears to be a sensible choice.

The old way was seriously broken and this needed to be workarounded with a temporary file. Maybe now is the time to make this work (or get rid of it completely).

If this is changed, it needs to support unloading modules, too. This should avoid any hw/sw-dependence on a singular machine and move such stuff to configuration.

There's also hidden bugs with this: Currently the submit platform must be identical with the run platform. You can't use modules in the queue if you're not using them locally. Bummer.  
Testing to write a submitscript on a different machine simply fails.

This all is not going to be a quick fix and unfortunately #33 doesn't really fix this, it just workarounds more of it.

### LINKED ISSUE #37: configure script typo
The `purge_modules` boolean is changed depending on user input in the configure script, but commented out (see line 789):
https://github.com/polyluxus/runxtb.bash/blob/bb6995ae12ec1d6af4a566f32515eb95a7b0fa00/configure/configure.sh#L777-L789

Should be solved by removing the pound sign.

### LINKED ISSUE #38: Previous hotfixed module unload can be removed
Currently, it is assumed that either `module purge` is an available command (relying on user during configuration) or that the module system does no funky per default loading of modules which conflict with the user's choice. 
Thus, we can also remove the following:
https://github.com/polyluxus/runxtb.bash/blob/bb6995ae12ec1d6af4a566f32515eb95a7b0fa00/runxtb.sh#L640-L643

### LINKED ISSUE #41: outdated link
https://github.com/polyluxus/runxtb.bash/blob/27420545e73b4461ecd74b7085c98e8ba5d60303/README.md?plain=1#L5

is now

https://www.chemie.uni-bonn.de/grimme/de/software/xtb

### LINKED ISSUE #43: found rogue question
https://github.com/polyluxus/runxtb.bash/blob/4a620960f09ffdf1a181b494a09c13cfb732b9dd/configure/configure.sh#L531

Currently no idea why this is here and where it actually belongs.

### LINKED ISSUE #44: Typo when purging modules
This should be `module purge` instead of `modules purge`

https://github.com/polyluxus/runxtb.bash/blob/2f7c27fcb3a529a091f67286cdc63b670a9fd2d4/runxtb.sh#L644

### LINKED ISSUE #45: crest not reading in the correct number of threads
When using `runxtb -p48 -C crest` the script will correctly set the queuing system parameters and export the correct environment variables for xtb. However, `crest` will not pick those environment variables up and only run with 4 processors. Not sure where that setting is coming from, though.

Example when using crest directly (exactly as in the generated submission script):
```
$ crest coord
...
 Estimated runtime for one MTD (9.0 ps) on a single thread: 7 min 46 sec
 Estimated runtime for a batch of 14 MTDs on 4 threads: 31 min 4 sec
...
```
Example when using crest explicitly with the `-T` option:
```
$ crest coord -T 24
...
 Estimated runtime for one MTD (9.0 ps) on a single thread: 17 min 30 sec
 Estimated runtime for a batch of 14 MTDs on 24 threads: 17 min 30 sec
...
```

### PR DESCRIPTION
**Pull request by polyluxus**
Switch usage of environment modules to Lmod

### CODE REVIEW

File: runxtb.sh [hunk 1]
```diff
@@ -827,10 +835,16 @@ while getopts :p:m:w:o:sSQ:P:Ml:iB:C:qhHX options ; do
...
     #hlp            If <ARG> is '0', then reset the list.
+    #hlp            If <ARG> is 'purge', all (by default) loaded modules will be unloaded,
+    #hlp            then the list will be reset.
+    #hlp            Please note that an empty list will cause the script to fail.
     #hlp            (Can also be set in the rc.)
     l)
       use_modules="true"
-      if [[ "$OPTARG" =~ ^[[:space:]]*([0]+)[[:space:]]?(.*)$ ]] ; then
+      if [[ "$OPTARG" =~ ^[[:space:]]*[Pp][Uu][Rr][Gg][Ee][[:space:]]*$ ]] ; then
+	purge_modules="true"
```
Comment (polyluxus) [inline runxtb.sh:853]: setting missing in display below L904

File: README.md [hunk 2]
```diff
@@ -163,4 +173,4 @@ See [LICENSE](LICENSE) to see the full text.
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-(Martin; 2024-01-07; wrapper version 0.5.0)
+(Martin; 2024-01-19; wrapper version 0.5.0.ea1)
```
Comment (polyluxus) [inline README.md]: wrong version

File: runxtb.rc [hunk 3]
```diff
@@ -80,14 +80,19 @@
...
+#  load_modules[0]="xtb"
+#  load_modules[1]="CREST"
 
 ## Set Walltime for non-interactive mode
 #
    requested_walltime="24:00:00"
 
 #
-## End of example runxtb.rc (Martin; 2024-01-07; wrapper version 0.5.0)
+## End of example runxtb.rc (Martin; 2024-01-19; wrapper version 0.5.0.ea1)
```
Comment (polyluxus) [inline runxtb.rc]: wrong version

File: runxtb.sh (hunk 1 above)
Comment (polyluxus) [reply runxtb.sh:853]: fixed

**Review by polyluxus — COMMENTED** [review]
looks good so far
